name: GitHub Actions 
run-name: ${{ github.actor }} test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Вывод содержимого директории
      run: |
        ls ${{ github.workspace }}
    - name: CMake Action
      uses: threeal/cmake-action@v2.1.0
    - name: Компиляция
      run: cmake -H. -Bbuild
    - name: Компиляция2
      run:  cmake --build build --target=package_all
    - name: Вывод содержимого директории
      run: |
        ls ${{ github.workspace }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
    - name: upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/linux-1.0.0-sources.tar.gz
        asset_name: linux-1.0.0-sources.tar.gz
        asset_content_type: application/gzip
    - name: upload  artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/linux-1.0.0-sources.zip
        asset_name: linux-1.0.0-sources.zip
        asset_content_type: application/zip
    - name: upload  artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/linux-1.0.0-bin.deb
        asset_name: linux-1.0.0-sources.deb
        asset_content_type: application/deb
