name: GitHub Actions 
run-name: ${{ github.actor }} test
on: [push]
jobs:
  Test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Вывод содержимого директории
      run: |
        ls ${{ github.workspace }}
    - name: CMake Action
      uses: threeal/cmake-action@v2.1.0
    - name: Компиляция
      run: cmake -H. -Bbuild
    - name: Компиляция2
      run:  cmake --build build --target=package_all
    - name: Вывод содержимого директории
      run: |
        ls build
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: tag_n${{ steps.version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/lab6-0.1.1-Linux-sources.tar.gz
        asset_name: lab6-0.1.1-Linux-sources.tar.gz
        asset_content_type: application/gzip
    - name: upload  artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/lab6-0.1.1-Linux-sources.zip
        asset_name: lab6-0.1.1-Linux-sources.zip
        asset_content_type: application/zip
    - name: upload  artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/lab6-0.1.1-Linux-bin.deb
        asset_name: lab6-0.1.1-Linux-bin.deb
        asset_content_type: application/deb
    - name: upload  artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/lab6-0.1.1-Linux-bin.rpm
        asset_name: lab6-0.1.1-Linux-bin.rpm
        asset_content_type: application/rpm 
